### ISSUE TITLE
SSL error on android 

### ISSUE THREAD

**Issue by tkkcc** [rust-lang/git2-rs#920]
Basic https fetch fails on genymotion android 10. Enable `vendored-openssl` doesn't help.

```txt
Git(Error { code: -17, klass: 16, message: "the SSL certificate is invalid" })
```
Dependency

```toml
reqwest = { version = "0.11", features =[ "blocking"] }
openssl = {version = "0.10", features = ["vendored"]}

# git2 = { version = "0.16.1"}
git2 = { version = "0.16.1", features = ["vendored-openssl"]}
```
BTW, reqwest https works.
